%% DIABETIC RETINOPATHY FINAL REPORT
% Uses the trained ResNet-50 model saved by trainDRModel.m

clear;
clc;
close all;

%% ============================================================
% PROJECT PATH
% ============================================================

projectFolder = fileparts(mfilename("fullpath"));

%% ============================================================
% LOAD TRAINED MODEL
% ============================================================

modelPath = fullfile( ...
    projectFolder, ...
    "models", ...
    "DR_ResNet50.mat");

if ~isfile(modelPath)
    error("Trained model not found: %s",modelPath);
end

fprintf("\nLoading trained ResNet-50 model...\n");

loadedData = load(modelPath,"trainedNet");

if ~isfield(loadedData,"trainedNet")
    error("The MAT file does not contain trainedNet.");
end

net = loadedData.trainedNet;

fprintf("Trained model loaded successfully.\n");
fprintf("Model type: %s\n",class(net));

%% ============================================================
% SELECT TEST IMAGE
% ============================================================

[fileName,filePath] = uigetfile( ...
    {'*.jpg;*.jpeg;*.png;*.bmp','Fundus Images'}, ...
    'Select Fundus Test Image');

if isequal(fileName,0)
    fprintf("No image selected.\n");
    return;
end

imagePath = fullfile(filePath,fileName);

fprintf("\nTest image:\n%s\n",imagePath);

%% ============================================================
% LOAD IMAGE
% ============================================================

originalImage = imread(imagePath);

if size(originalImage,3) == 1
    originalImage = cat(3, ...
        originalImage, ...
        originalImage, ...
        originalImage);
end

%% ============================================================
% PREPROCESS IMAGE
% ============================================================

img = imresize(originalImage,[224 224]);

img = im2single(img);

%% ============================================================
% CREATE BATCH DIMENSION
% ============================================================

imgBatch = reshape(img,224,224,3,1);

dlImg = dlarray(imgBatch,"SSCB");

%% ============================================================
% MODEL PREDICTION
% ============================================================

fprintf("\nRunning trained model...\n");

scores = predict(net,dlImg);

scores = extractdata(scores);

scores = double(scores);

scores = squeeze(scores);

scores = scores(:);

%% ============================================================
% CONVERT OUTPUT TO PROBABILITIES
% ============================================================

probabilities = double(scores(:));

%% ============================================================
% CLASS INFORMATION
% ============================================================

classNames = [ ...
    "No DR", ...
    "Mild", ...
    "Moderate", ...
    "Severe", ...
    "Proliferative DR"];

%% ============================================================
% CHECK NUMBER OF CLASSES
% ============================================================

if numel(probabilities) ~= 5

    error( ...
        "Model returned %d classes instead of 5.", ...
        numel(probabilities));

end

%% ============================================================
% PREDICT CLASS
% ============================================================

[confidence,predictedIndex] = max(probabilities);

predictedGrade = predictedIndex - 1;

predictedLabel = classNames(predictedIndex);

%% ============================================================
% DISPLAY RESULTS
% ============================================================

fprintf("\n");
fprintf("============================================\n");
fprintf("       DIABETIC RETINOPATHY RESULT\n");
fprintf("============================================\n");

fprintf("Image      : %s\n",fileName);

fprintf("Prediction : Grade %d (%s)\n", ...
    predictedGrade, ...
    predictedLabel);

fprintf("Confidence : %.2f%%\n", ...
    confidence * 100);

fprintf("\nClass probabilities:\n");

for k = 1:5

    fprintf( ...
        "Grade %d (%s): %.2f%%\n", ...
        k - 1, ...
        classNames(k), ...
        probabilities(k) * 100);

end

fprintf("============================================\n");

%% ============================================================
% GRAD-CAM
% ============================================================

fprintf("\nGenerating Grad-CAM...\n");

try

    featureLayer = "res5c_branch2c";

    scoreMap = gradCAM( ...
        net, ...
        img, ...
        predictedIndex, ...
        "FeatureLayer", ...
        featureLayer);

catch

    fprintf("Specified feature layer unavailable.\n");
    fprintf("Using automatic Grad-CAM layer selection.\n");

    scoreMap = gradCAM( ...
        net, ...
        img, ...
        predictedIndex);

end

%% ============================================================
% NORMALIZE GRAD-CAM
% ============================================================

scoreMap = imresize( ...
    scoreMap, ...
    [224 224]);

scoreMap = double(scoreMap);

scoreMap = scoreMap - min(scoreMap(:));

maxScore = max(scoreMap(:));

if maxScore > 0

    scoreMap = scoreMap ./ maxScore;

end

%% ============================================================
% CREATE RETINAL MASK
% ============================================================

grayImage = rgb2gray( ...
    imresize(originalImage,[224 224]));

retinaMask = grayImage > 10;

retinaMask = imfill( ...
    retinaMask, ...
    "holes");

retinaMask = bwareafilt( ...
    retinaMask, ...
    1);

%% ============================================================
% CREATE HIGH ACTIVATION REGIONS
% ============================================================

camRetina = scoreMap;

camRetina(~retinaMask) = 0;

threshold = 0.90;

regionMask = camRetina >= threshold;

regionMask = regionMask & retinaMask;

regionMask = bwareaopen( ...
    regionMask, ...
    15);

regionMask = imdilate( ...
    regionMask, ...
    strel("disk",2));

stats = regionprops( ...
    regionMask, ...
    "BoundingBox", ...
    "Area");

%% ============================================================
% CREATE RESULT FOLDER
% ============================================================

resultFolder = fullfile( ...
    filePath, ...
    "DR_Results");

if ~isfolder(resultFolder)

    mkdir(resultFolder);

end

[~,imageName,~] = fileparts(fileName);

%% ============================================================
% CREATE FINAL REPORT
% ============================================================

fig = figure( ...
    "Name","Diabetic Retinopathy Final Report", ...
    "Color",[0.06 0.06 0.06], ...
    "Position",[50 50 1700 850]);

%% ============================================================
% ORIGINAL IMAGE
% ============================================================

ax1 = axes( ...
    "Parent",fig, ...
    "Position",[0.02 0.10 0.29 0.76]);

imshow( ...
    imresize(originalImage,[224 224]), ...
    "Parent",ax1);

axis(ax1,"image");
axis(ax1,"off");

title( ...
    ax1, ...
    "Original Fundus Image", ...
    "Color","white", ...
    "FontSize",15, ...
    "FontWeight","bold");

%% ============================================================
% GRAD-CAM
% ============================================================

ax2 = axes( ...
    "Parent",fig, ...
    "Position",[0.33 0.10 0.29 0.76]);

imshow( ...
    repmat(grayImage,[1 1 3]), ...
    "Parent",ax2);

hold(ax2,"on");

camImage = imagesc( ...
    ax2, ...
    scoreMap);

camImage.AlphaData = 0.38;

colormap(ax2,jet);

%% ============================================================
% DRAW ATTENTION BOXES
% ============================================================

numRegions = 0;

if ~isempty(stats)

    areas = [stats.Area];

    [~,order] = sort( ...
        areas, ...
        "descend");

    maxRegions = min(3,numel(order));

    for k = 1:maxRegions

        s = stats(order(k));

        if s.Area < 50
            continue;
        end

        numRegions = numRegions + 1;

        rectangle( ...
            ax2, ...
            "Position",s.BoundingBox, ...
            "EdgeColor","black", ...
            "LineWidth",3);

        text( ...
            ax2, ...
            s.BoundingBox(1), ...
            max(1,s.BoundingBox(2)-5), ...
            sprintf("%d",numRegions), ...
            "Color","white", ...
            "FontSize",13, ...
            "FontWeight","bold", ...
            "BackgroundColor","black", ...
            "Margin",2);

    end

end

axis(ax2,"image");
axis(ax2,"off");

title( ...
    ax2, ...
    "Grad-CAM and Attention Regions", ...
    "Color","white", ...
    "FontSize",15, ...
    "FontWeight","bold");

hold(ax2,"off");

cb = colorbar(ax2);

cb.Label.String = ...
    "Grad-CAM Activation";

cb.Label.Color = "white";

cb.Color = "white";

%% ============================================================
% REPORT INFORMATION
% ============================================================

ax3 = axes( ...
    "Parent",fig, ...
    "Position",[0.70 0.10 0.28 0.76]);

axis(ax3,[0 1 0 1]);

axis(ax3,"off");

%% TITLE

text( ...
    ax3, ...
    0.02, ...
    0.96, ...
    "DIABETIC RETINOPATHY", ...
    "Color","white", ...
    "FontSize",22, ...
    "FontWeight","bold", ...
    "VerticalAlignment","top");

text( ...
    ax3, ...
    0.02, ...
    0.89, ...
    "AI-Based Fundus Image Assessment", ...
    "Color",[0.75 0.75 0.75], ...
    "FontSize",12, ...
    "VerticalAlignment","top");

line( ...
    ax3, ...
    [0.02 0.98], ...
    [0.84 0.84], ...
    "Color",[0.4 0.4 0.4], ...
    "LineWidth",1);

%% PREDICTION

text( ...
    ax3, ...
    0.02, ...
    0.76, ...
    sprintf( ...
    "Predicted DR Grade: %d (%s)", ...
    predictedGrade, ...
    predictedLabel), ...
    "Color","white", ...
    "FontSize",16, ...
    "FontWeight","bold", ...
    "VerticalAlignment","top");

%% CONFIDENCE

text( ...
    ax3, ...
    0.02, ...
    0.68, ...
    sprintf( ...
    "Confidence: %.2f%%", ...
    confidence * 100), ...
    "Color","white", ...
    "FontSize",16, ...
    "VerticalAlignment","top");

%% ATTENTION REGIONS

text( ...
    ax3, ...
    0.02, ...
    0.60, ...
    sprintf( ...
    "Attention Regions: %d", ...
    numRegions), ...
    "Color",[0.8 0.8 0.8], ...
    "FontSize",14, ...
    "VerticalAlignment","top");

%% THRESHOLD

text( ...
    ax3, ...
    0.02, ...
    0.53, ...
    sprintf( ...
    "Activation Threshold: %.0f%%", ...
    threshold * 100), ...
    "Color",[0.8 0.8 0.8], ...
    "FontSize",14, ...
    "VerticalAlignment","top");

line( ...
    ax3, ...
    [0.02 0.98], ...
    [0.47 0.47], ...
    "Color",[0.4 0.4 0.4], ...
    "LineWidth",1);

%% EXPLANATION

text( ...
    ax3, ...
    0.02, ...
    0.40, ...
    {"Black boxes indicate", ...
     "high-activation regions", ...
     "identified by Grad-CAM."}, ...
    "Color","white", ...
    "FontSize",13, ...
    "FontWeight","bold", ...
    "VerticalAlignment","top");

%% CLASS PROBABILITIES

text( ...
    ax3, ...
    0.02, ...
    0.27, ...
    "Class Probabilities", ...
    "Color","white", ...
    "FontSize",13, ...
    "FontWeight","bold", ...
    "VerticalAlignment","top");

probabilityY = 0.22;

for k = 1:5

    text( ...
        ax3, ...
        0.02, ...
        probabilityY, ...
        sprintf( ...
        "Grade %d: %s %.2f%%", ...
        k - 1, ...
        classNames(k), ...
        probabilities(k) * 100), ...
        "Color",[0.8 0.8 0.8], ...
        "FontSize",10, ...
        "VerticalAlignment","top");

    probabilityY = probabilityY - 0.032;

end

%% DISCLAIMER

text( ...
    ax3, ...
    0.02, ...
    0.035, ...
    "AI-assisted analysis - not a medical diagnosis.", ...
    "Color",[0.6 0.6 0.6], ...
    "FontSize",10, ...
    "VerticalAlignment","bottom");

%% ============================================================
% MAIN REPORT TITLE
% ============================================================

annotation( ...
    fig, ...
    "textbox", ...
    [0.02 0.90 0.96 0.07], ...
    "String",sprintf( ...
    "DR Severity Analysis | Grade %d (%s) | Confidence %.2f%%", ...
    predictedGrade, ...
    predictedLabel, ...
    confidence * 100), ...
    "Color","white", ...
    "FontSize",19, ...
    "FontWeight","bold", ...
    "HorizontalAlignment","center", ...
    "VerticalAlignment","middle", ...
    "EdgeColor","none");

%% ============================================================
% SAVE ONLY ONE REPORT IMAGE
% ============================================================

reportPath = fullfile( ...
    resultFolder, ...
    [imageName "_DR_Severity_Report.png"]);

drawnow;

exportgraphics(fig,reportPath);

%% ============================================================
% VERIFY FILE
% ============================================================

if ~isfile(reportPath)

    error( ...
        "Report was not saved: %s", ...
        reportPath);

end

fprintf("\n");
fprintf("============================================\n");
fprintf("       REPORT GENERATION COMPLETE\n");
fprintf("============================================\n");

fprintf("Model       : DR_ResNet50.mat\n");
fprintf("Test Image  : %s\n",fileName);

fprintf("Prediction  : Grade %d (%s)\n", ...
    predictedGrade, ...
    predictedLabel);

fprintf("Confidence  : %.2f%%\n", ...
    confidence * 100);

fprintf("Report saved:\n");
fprintf("%s\n",reportPath);

fprintf("============================================\n");

%% ============================================================
% OPEN RESULT FOLDER
% ============================================================

if ispc

    try

        winopen(resultFolder);

    catch

        fprintf("Could not open result folder automatically.\n");

    end

end